Title: CriticNous Official Website
author: CriticNous Team, theo dõi chúng tớ tại <a href="https://www.youtube.com/@Criticnous">Youtube@Criticnous</a> 

execute:
  execute_notebooks: "auto"

only_build_toc_files: true

html:
  favicon : "logo_circled.png"
  baseurl :  "https://criticnous.github.io" #Replace this with your own URL

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      logo:
        text: CriticNous
        image_light: logo_circled.png # Put your logo for the light mode here (can be the same as image_dark)
        image_dark: logo_circled.png # Put your logo for the dark mode here (can be the same as image_light)
      repository_url: "https://github.com/criticnous/criticnous.github.io" #add your own repo URL here
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: true
      use_repository_button: false
      use_issues_button : false
      launch_buttons:
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
    html_static_path: ["figure"] # add folders that contain files that need to be included, such as the location of the logo(s)
    mathjax3_config:
      chtml: {
        mtextInheritFont: true # To typeset text within math prettier
      }
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter
    - sphinx_exercise
    - teachbooks_sphinx_tippy

bibtex_bibfiles: 
  - references.bib
